const contractAddress = "0xbd8147EFf984F70c723B442412E6A8968551a568"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the fucking test of PolyRaffle website frontend!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'PolyRaffle is a decentralized lottery aimed at being trustless and provide the best odds and hightest payout percentage out there';
const h1_presale_coming_soon = "NFT Drop Coming Soon probably lol";
const h1_presale_mint = "Pre-Sale Minting will be open to insider trading lmao";
const h1_public_mint = "Public Minting Open fo the next 10 seconds prob (we will sell out fast lol)";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
